#!/bin/sh

raw=`df -HBG /home/yli/e | grep /dev/`

case $1 in
    "--used" )
        value=`echo $raw | awk '{print $3}'`
        ;;
    "--all" )
        value=`echo $raw | awk '{print $2}'`
        ;;
    "--free" )
        value=`echo $raw | awk '{print $4}'`
        ;;
    * )
        true
        ;;
esac
value=${value::-1}
echo $value
