#!/bin/sh

total=`wmctrl -d | wc -l`    
icon1=○
icon2=◎
icon3=●
eww="eww -c $HOME/.config/eww/mybar/"

while true; do
	currwp=$((`wmctrl -d | grep '*' | cut -c1`))
	for (( i = 0; i < $total; i++));    
	do    
	    if [[ $i -eq $currwp ]]    
	    then    
	        $eww update wp$i=$icon3    
	    else    
	        $eww update wp$i=$icon1     
	    fi;    
	done
	echo cycle
done
